version: '3'

networks:
  backend:
    driver: bridge
  kafka_broker:
    external: true

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html
    working_dir: /var/www/html
    tty: true
    networks:
      - kafka_broker
      - backend

  postgres:
    build:
      context: ./docker/postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - kafka_broker
      - backend
      
  pgadmin:
    build: ./docker/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    volumes:
      - ${DATA_PATH_HOST}/pgadmin:/var/lib/pgadmin
    networks:
      - backend